---
# task: create the secretstore
#       e.g. HashiCorp Vault
#
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: "http://vault.vault.svc:8200"
      path: "secret"
      version: "v2"
      auth:
        # points to a secret that contains a vault token
        # https://www.vaultproject.io/docs/auth/token
        tokenSecretRef:
          name: "vault-token"
          key: "token"
---
# task: HashiCorp Vault with token
#       see more at https://external-secrets.io/v0.5.9/provider-hashicorp-vault/#authentication
#
apiVersion: v1
kind: Secret
metadata:
  name: vault-token
data:
  token: cm9vdA== # value="root" use for vault, dev installation
---
# task: create external-secret for wordpress
#
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: wordpress-password
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: site-wordpress
  data:
  - secretKey: wordpress-password
    remoteRef:
      key: secret/wordpress
      property: wordpress-password
---
# task: create external-secret for mariadb
#
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mariadb-password
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: site-mariadb
  dataFrom:
  - extract:
      key: mariadb
